ALTER TABLE job ADD COLUMN required_count INTEGER NOT NULL DEFAULT 1;
ALTER TABLE job ADD COLUMN category VARCHAR(40) NOT NULL DEFAULT '其他';
ALTER TABLE job ADD COLUMN requirements VARCHAR(2000) NOT NULL DEFAULT '发布者暂未补充工作要求';
ALTER TABLE job ADD COLUMN starts_at TIMESTAMP NULL;
ALTER TABLE job ADD COLUMN duration_minutes INTEGER NULL;
ALTER TABLE job ADD COLUMN pay_unit VARCHAR(10) NOT NULL DEFAULT 'DAY';
ALTER TABLE job MODIFY COLUMN pay DECIMAL(12,2) NOT NULL;
UPDATE job SET required_count = CASE WHEN (SELECT COUNT(*) FROM job_application a WHERE a.job_id=job.id)>1 THEN (SELECT COUNT(*) FROM job_application a WHERE a.job_id=job.id) ELSE 1 END;
