CREATE TABLE review_admin (
  id VARCHAR(36) PRIMARY KEY,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  display_name VARCHAR(60) NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE review_action (
  id VARCHAR(36) PRIMARY KEY,
  admin_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  review_id VARCHAR(36) NOT NULL UNIQUE,
  decision VARCHAR(16) NOT NULL,
  note VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(admin_id) REFERENCES review_admin(id),
  FOREIGN KEY(user_id) REFERENCES account_identity(id)
) ENGINE=InnoDB;
