<script setup>
import { ref, reactive, onMounted, onUnmounted } from 'vue'
import { api } from '../../api'
const admin=ref(null),ready=ref(false),busy=ref(false),error=ref(''),success=ref(''),tab=ref('pending'),role=ref('ALL')
const credentials=reactive({username:'',password:''}),result=ref({items:[],total:0,page:0}),detail=ref(null),note=ref(''),decision=ref(null)
const labels={PUBLISHER:'企业发布者',STUDENT:'学生领取者',PENDING:'待审核',APPROVED:'已通过',REJECTED:'已驳回'}
const time=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—'
async function action(fn){if(busy.value)return;busy.value=true;error.value='';success.value='';try{await fn()}catch(e){error.value=e.message;if(e.status===401){admin.value=null;detail.value=null;note.value='';decision.value=null;result.value={items:[],total:0,page:0}}}finally{busy.value=false}}
async function load(page=0){result.value=await api(tab.value==='pending'?`/admin/reviews?role=${role.value}&page=${page}`:`/admin/history?page=${page}`)}
function login(){action(async()=>{await api('/admin/login',{method:'POST',body:credentials});credentials.password='';admin.value=await api('/admin/me');await load()})}
function logout(){action(async()=>{await api('/admin/logout',{method:'POST'});admin.value=null;detail.value=null;decision.value=null;note.value='';result.value={items:[],total:0,page:0}})}
function switchTab(next){tab.value=next;close();action(()=>load())}
function close(){detail.value=null;note.value='';decision.value=null}
function open(id){action(async()=>{close();detail.value=await api('/admin/reviews/'+id)})}
function prepare(approved){if(!note.value.trim()){error.value='请填写审核意见，驳回时应说明需要修改的内容';return}decision.value=approved}
function submit(){action(async()=>{await api(`/admin/reviews/${detail.value.id}/decision`,{method:'POST',body:{reviewId:detail.value.review_id,approved:decision.value,note:note.value}});close();await load();success.value='审核结果已保存，用户权限同步更新'})}
let timer
onMounted(async()=>{await action(async()=>{admin.value=await api('/admin/me');await load()});error.value='';ready.value=true;timer=setInterval(()=>{if(admin.value&&!busy.value)action(async()=>{admin.value=await api('/admin/me')})},60000)})
onUnmounted(()=>{clearInterval(timer);close()})
</script>
<template>
  <div class="review-app">
    <header class="review-top"><div><strong>贝鱼 · 实名认证审核</strong><p>人工审核工作台</p></div><div v-if="admin" class="button-row"><span>{{admin.display_name}}</span><button class="secondary" :disabled="busy" @click="logout">退出登录</button></div><a v-else href="/publisher">返回发布端 ↗</a></header>
    <main class="review-main">
      <p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="success" class="alert success" role="status">{{success}}</p>
      <div v-if="!ready" class="empty-state">正在加载…</div>
      <section v-else-if="!admin" class="panel review-login"><span class="eyebrow">REVIEW ACCESS</span><h1>审核员登录</h1><p>使用独立审核账号进入，企业和学生账号无法登录此端。</p><form @submit.prevent="login"><label>审核账号<input v-model.trim="credentials.username" autocomplete="username" maxlength="60" required /></label><label>密码<input v-model="credentials.password" type="password" autocomplete="current-password" maxlength="64" required /></label><button class="primary" :disabled="busy">{{busy?'登录中…':'登录审核端'}}</button></form></section>
      <template v-else>
        <nav class="review-tabs"><button :class="{active:tab==='pending'}" :disabled="busy" @click="switchTab('pending')">待审核申请</button><button :class="{active:tab==='history'}" :disabled="busy" @click="switchTab('history')">审核记录</button></nav>
        <section class="panel review-list"><div class="section-title"><h2>{{tab==='pending'?'待审核申请':'人工审核记录'}} · {{result.total}}</h2><div class="button-row"><select v-if="tab==='pending'" v-model="role" aria-label="筛选身份" :disabled="busy" @change="action(()=>load())"><option value="ALL">全部身份</option><option value="PUBLISHER">企业发布者</option><option value="STUDENT">学生领取者</option></select><button class="secondary" :disabled="busy" @click="action(()=>load(result.page))">刷新</button></div></div>
          <div v-if="!result.items.length" class="empty-state">{{busy?'加载中…':tab==='pending'?'暂无待审核申请':'暂无人工审核记录'}}</div>
          <article v-for="item in result.items" :key="item.id" class="review-row"><div><span class="outline-tag">{{labels[item.role]}}</span><h3>{{item.affiliation || '未填写单位 / 学校'}}</h3><p>{{item.nickname || '未设置昵称'}} · {{time(item.submitted_at||item.created_at)}}</p><template v-if="tab==='history'"><p>{{labels[item.decision]}} · 审核员：{{item.reviewer}}</p><p class="review-note">{{item.note}}</p></template></div><button v-if="tab==='pending'" class="primary" :disabled="busy" @click="open(item.id)">查看并审核</button></article>
          <div class="pagination"><button class="secondary" :disabled="busy||result.page===0" @click="action(()=>load(result.page-1))">上一页</button><span>{{result.page+1}} / {{Math.max(1,Math.ceil(result.total/20))}}</span><button class="secondary" :disabled="busy||(result.page+1)*20>=result.total" @click="action(()=>load(result.page+1))">下一页</button></div>
        </section>
        <div v-if="detail" class="modal-backdrop"><section class="panel modal review-detail" role="dialog" aria-modal="true" aria-label="实名认证资料审核"><div class="section-title"><h2>{{labels[detail.role]}}资料</h2><button class="secondary" :disabled="busy" @click="close">关闭</button></div><p class="review-warning">以下为用户提交的敏感资料，仅用于实名认证核验。审核意见不要填写身份证号、姓名或学号原文。</p><dl><template v-if="detail.role==='PUBLISHER'"><dt>单位名称</dt><dd>{{detail.organization}}</dd><dt>姓氏</dt><dd>{{detail.surname}}</dd><dt>名字</dt><dd>{{detail.name}}</dd><dt>身份证号</dt><dd>{{detail.identityNumber}}</dd></template><template v-else><dt>学校</dt><dd>{{detail.school}}</dd><dt>姓名</dt><dd>{{detail.name}}</dd><dt>学号</dt><dd>{{detail.studentNumber}}</dd></template></dl><h3>最近认证记录</h3><p v-for="(event,index) in detail.events" :key="index" class="review-note">{{labels[event.status]}} · {{time(event.created_at)}}<br/>{{event.note}}</p><label>审核意见（必填）<textarea v-model.trim="note" :disabled="busy||decision!==null" maxlength="500" rows="3" placeholder="如：资料核验通过；或说明驳回原因及修改要求" /></label><p v-if="error" class="alert error" role="alert">{{error}}</p><div v-if="decision===null" class="button-row"><button class="primary" :disabled="busy" @click="prepare(true)">通过审核</button><button class="secondary" :disabled="busy" @click="prepare(false)">驳回申请</button></div><div v-else class="review-confirm"><p>确认{{decision?'通过并开通发布 / 接取权限':'驳回该申请，允许用户修改后重提'}}？</p><div class="button-row"><button class="primary" :disabled="busy" @click="submit">{{busy?'保存中…':'确认提交'}}</button><button class="secondary" :disabled="busy" @click="decision=null">返回修改</button></div></div></section></div>
      </template>
    </main>
  </div>
</template>
<style scoped>
.review-app{min-height:100vh;background:#f4f7f4}.review-top{background:white;border-bottom:1px solid #e1e8e1;padding:22px max(24px,calc((100vw - 1120px)/2));display:flex;justify-content:space-between;align-items:center;gap:18px}.review-top strong{font-size:20px}.review-top p,.review-row p{color:#7b877f;font-size:13px}.review-main{max-width:1168px;margin:auto;padding:32px 24px}.review-login{max-width:440px;margin:60px auto;padding:36px}.review-login h1{margin:12px 0}.review-login p{color:#738078;margin:12px 0 24px}.review-login button{width:100%}.review-tabs{display:flex;gap:12px;margin-bottom:22px}.review-tabs button{padding:12px 22px;border-radius:9px;background:#e8eee8;color:#4b6455}.review-tabs .active{background:#2d7353;color:white}.review-list{padding:26px}.review-row{padding:22px 0;border-bottom:1px solid #e8ede8;display:flex;justify-content:space-between;gap:16px;align-items:center}.review-row h3{margin:10px 0}.review-list select{padding:10px;border:1px solid #d8e1d8;border-radius:8px;background:white}.review-detail{width:640px}.review-detail dl{display:grid;grid-template-columns:100px 1fr;gap:12px;margin:24px 0}.review-detail dd{margin:0;overflow-wrap:anywhere}.review-detail dt{color:#738078}.review-warning,.review-confirm{padding:14px;background:#f4f5e9;border-radius:10px;font-size:13px;line-height:1.8}.review-note{white-space:pre-wrap;overflow-wrap:anywhere;margin:10px 0 16px}.review-detail label{margin-top:20px}.review-detail .primary{width:auto}.review-confirm .button-row{margin-top:14px}@media(max-width:600px){.review-top{padding:18px;align-items:flex-start}.review-top strong{font-size:16px}.review-main{padding:20px 14px}.review-list{padding:18px}.review-list .section-title,.review-row{align-items:flex-start;flex-direction:column}.review-login{margin:20px auto;padding:24px}}
</style>
