<script setup>
import {ref,onMounted} from 'vue'
import {api} from '../api'
import {newRequestKey} from '../requestKey'
const props=defineProps({user:Object})
const emit=defineEmits(['expired'])
const data=ref(null),busy=ref(false),error=ref(''),success=ref(''),amount=ref(''),requestKey=ref(newRequestKey())
const labels={TOP_UP:'模拟充值',JOB_PAY:'兼职费发放',JOB_INCOME:'兼职费收入',WITHDRAW_HOLD:'提现冻结',WITHDRAW_RELEASE:'撤销提现'}
const money=cents=>((cents||0)/100).toFixed(2)
async function load(page=0){data.value=await api('/wallet?page='+page)}
async function action(fn){if(busy.value)return;busy.value=true;error.value='';success.value='';try{await fn()}catch(e){error.value=e.message;if(e.status===401)emit('expired')}finally{busy.value=false}}
function submit(){action(async()=>{await api(props.user.role==='PUBLISHER'?'/wallet/top-up':'/wallet/withdrawals',{method:'POST',body:{amount:amount.value,requestKey:requestKey.value}});requestKey.value=newRequestKey();amount.value='';success.value=props.user.role==='PUBLISHER'?'模拟充值成功':'提现申请已提交，资金已冻结；当前不会实际到账';await load()})}
function cancel(item){action(async()=>{item.cancelKey ||= newRequestKey();await api(`/wallet/withdrawals/${item.id}/cancel`,{method:'POST',body:{requestKey:item.cancelKey}});success.value='已撤销提现，冻结余额已退回';await load(data.value.page)})}
onMounted(()=>action(()=>load()))
</script>
<template>
  <div class="wallet-layout"><section class="panel personal-card"><div class="section-title"><div><h2>{{user.role==='STUDENT'?'我的钱包':'企业结算钱包'}}</h2><p>每一笔收支，都清晰可查。</p></div><button class="secondary" :disabled="busy" @click="action(()=>load(data?.page||0))">刷新</button></div><p class="simulation-banner">模拟资金 · 不是真实人民币余额 · 无真实充值、扣款或银行到账</p><p v-if="error" class="alert error" role="alert">{{error}}</p><p v-if="success" class="alert success" role="status">{{success}}</p><template v-if="data"><div class="wallet-balance"><div><small>可用模拟余额（元）</small><strong>¥{{money(data.balance_cents)}}</strong></div><div><small>提现冻结（元）</small><b>¥{{money(data.frozen_cents)}}</b></div></div><form class="wallet-form" @submit.prevent="submit"><label>{{user.role==='PUBLISHER'?'模拟充值金额':'提现申请金额'}}（元）<input v-model="amount" type="number" min="0.01" max="100000" step="0.01" placeholder="0.00" required :disabled="busy" @input="requestKey=newRequestKey()" /></label><button class="primary" :disabled="busy||data.mode!=='SIMULATED'">{{busy?'处理中…':user.role==='PUBLISHER'?'模拟充值':'申请提现'}}</button></form><p class="profile-note">{{user.role==='PUBLISHER'?'充值仅增加测试资金。请到岗位发布记录查看接取人并发放兼职费。':'申请后金额从可用余额转为冻结余额，状态为待处理。可以撤销退回；真实支付尚未接入。'}}</p></template><div v-else class="empty-state">{{busy?'正在加载钱包…':'钱包加载失败，请刷新重试'}}</div></section>
    <section v-if="data" class="panel personal-card ledger-panel"><div class="section-title"><h2>余额变动明细</h2><span>共 {{data.total}} 笔</span></div><div v-if="!data.entries.length" class="empty-state">暂无收支记录</div><article v-for="entry in data.entries" :key="entry.id" class="ledger-row"><div><strong>{{labels[entry.kind]||entry.kind}}</strong><p>{{entry.description}}</p><small>{{new Date(entry.created_at).toLocaleString('zh-CN')}}</small></div><div class="ledger-amount"><strong :class="entry.delta_cents>0?'income':'expense'">{{entry.delta_cents>0?'+':''}}{{money(entry.delta_cents)}}</strong><small>可用 ¥{{money(entry.balance_after_cents)}}</small><small v-if="entry.frozen_delta_cents">冻结 {{entry.frozen_delta_cents>0?'+':''}}{{money(entry.frozen_delta_cents)}}</small></div></article><div class="pagination"><button class="secondary" :disabled="busy||data.page===0" @click="action(()=>load(data.page-1))">上一页</button><span>{{data.page+1}} / {{Math.max(1,Math.ceil(data.total/20))}}</span><button class="secondary" :disabled="busy||(data.page+1)*20>=data.total" @click="action(()=>load(data.page+1))">下一页</button></div></section>
    <section v-if="data&&user.role==='STUDENT'" class="panel personal-card withdrawals-panel"><h2>提现申请 <small class="optional">最近20条</small></h2><div v-if="!data.withdrawals.length" class="empty-state">暂无提现申请</div><article v-for="item in data.withdrawals" :key="item.id" class="history-row"><div><h3>¥{{money(item.amount_cents)}}</h3><small>{{new Date(item.created_at).toLocaleString('zh-CN')}}</small><p>{{item.status==='PENDING'?'待处理 · 模拟申请，未到账':'已撤销 · 冻结金额已退回'}}</p></div><button v-if="item.status==='PENDING'" class="secondary" :disabled="busy" @click="cancel(item)">撤销申请</button></article></section>
  </div>
</template>
